[project]
name = "renewable-energy-trading"
authors = ["adrianscott9447@gmail.com"]
description = "Tokenised renewable energy trading platform on Stacks blockchain"
telemetry = false
cache_dir = "./.clarinet"

[[project.boot_accounts]]
name = "deployer"
address = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 100000000

[[project.boot_accounts]]
name = "wallet_1"
address = "ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5"
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild"
balance = 100000000

[[project.boot_accounts]]
name = "wallet_2"
address = "ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG"
mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay hospital"
balance = 100000000

[contracts.energy-trading]
path = "contracts/energy-trading.clar"

[contracts.energy-certificates]
path = "contracts/energy-certificates.clar"
