[network]
name = "devnet"
node_rpc_address = "http://localhost:20443"
deployment_fee_rate = 10

[[network.accounts]]
name = "deployer"
address = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"
balance = 1000000000

[[network.accounts]]
name = "wallet_1"
address = "ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5"
balance = 1000000000

[[network.accounts]]
name = "wallet_2" 
address = "ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG"
balance = 1000000000

[repl.analysis.passes.check_checker]
trusted_sender = false
trusted_caller = false